apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-backup
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: busybox:1.28
              command: ["sh", "-c", "echo 'Running backup at $(date)'; sleep 10"]
