apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app-secrets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-app-secrets
  template:
    metadata:
      labels:
        app: db-app-secrets
    spec:
      containers:
        - name: db-container-secrets
          image: nginx:1.21
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-imperative  
                  key: DB_PASSWORD
          envFrom:
            - secretRef:
                name: db-secret-declarative
