apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: prod
spec:
  serviceAccountName: my-app-sa   # assign the SA
  containers:
  - name: app
    image: curlimages/curl
    command: ["sleep", "3600"]
