apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1m"
          memory: "1Mi"
        limits:
          cpu: "2m"
          memory: "2Mi"
