apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod9
  labels:
    app: demo
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod9-service
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
